sudo: false
language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
script:
  - python2.4 -m compileall -fq -x 'cloud/|monitoring/zabbix.*\.py|/layman.py|/maven_artifact.py|clustering/consul.*\.py' .
